changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Enhancements
      labels:
        - enhancement
    - title: 🩹 Fixes
      labels:
        - bug
    - title: 💅 Refactors
      labels:
        - refactoring
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 🔧 Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
