name: Codacy Analysis CLI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  codacy-analysis-cli:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['20.x']
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: pnpm install

      - run: pnpm postinstall

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
